import "./globals.css";
import MainContent from "../components/MainContent/MainContent.js";
import Sidebar from "../components/sidebar/Sidebar.js";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        style={{
          fontFamily: dmSans.style.fontFamily.split(",")[0] + "!important",
        }}
        className={dmSans.className + " h-full"}
      >
        <div className="flex h-full">
          <Sidebar></Sidebar>
          <MainContent>{children}</MainContent>
        </div>
      </body>
    </html>
  );
}
