import "./globals.css";
import MainContent from "../components/MainContent/MainContent.js";
import Sidebar from "../components/sidebar/Sidebar.js";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full"}>
        <div className="flex h-full">
          <Sidebar></Sidebar>
          <MainContent>{children}</MainContent>
        </div>
      </body>
    </html>
  );
}
